version: "3"
services:
  mynode: 
    container_name: mynode
    build: .
    ports: 
      - "8000:3000"
    depends_on:
     - mymongo

  mymongo: 
    container_name: mymongo
    image: mongo:latest  
    volumes:
    - /mongodb/database:/data/db 